feat: 7 hero component
ahmadsultani/coder-fe pull request #3
Opened 2023-08-21 10:05 UTC by fadillahumarr

2023-08-21 16:32 UTC, ahmadsultani requested changes

2023-08-21 16:32 UTC, ziru-tan commented on app/_components/organisms/Hero.tsx
> +    <section className="flex items-center w-full pl-16">
1. better pake gap di sini aja
2. mending py-8 di sini juga karena keduanya sama daripada diatur satu satu tiap section

2023-08-21 16:32 UTC, ziru-tan commented on app/_components/organisms/Hero.tsx
> +        <section className="flex w-[146px] px-4 py-3 rounded-[4px] gap-1 text-heading-s bg-primary-normal hover:bg-primary-normal-hover">
1. button jangan difixkan widthnya, atur pake padding saja,
2. ini juga harusnya button, dalamnya span sama image aja

2023-08-21 16:32 UTC, ziru-tan commented on app/_components/organisms/Hero.tsx
> +        <h1 className="font-bold text-heading-m text-neutral-dark-active ">
lebih cocok ini jadi header, dalamnya ada span sama h1

2023-08-21 16:32 UTC, ziru-tan commented on app/_components/organisms/Hero.tsx
> +        <p className="py-6 text-text-l text-justify">
jangan pake py-6 di sini, better pake gap-6 di parent

2023-08-21 16:32 UTC, ziru-tan commented on app/globals.css
> +body{
kasih juga width 100vw

2023-08-21 16:32 UTC, ziru-tan commented on app/page.tsx
> +import HeroSection from "./_components/organisms/Hero";
pake dynamic import

2023-08-21 16:32 UTC, ziru-tan commented on app/_components/organisms/Hero.tsx
> +      <section className=" w-1/2">
dalam case ini, lebih baik widthnya text dikasih flex-1 saja. bagusnya memang kalau ada 2 child seperti ini lebih bagus satunya ji dikasih fix width, satunya dikasih flex-1 biar ngefill ruang kosong.

2023-08-21 16:32 UTC, ziru-tan commented on app/_components/organisms/Hero.tsx
> +      <section className=" w-1/2 right-0 py-8 pl-24">
ini tidak usah plnya, atur gap di parent saja

2023-08-23 16:21 UTC, ahmadsultani approved these changes
GG

2023-08-23 16:23 UTC, merged